### ISSUE TITLE
No data during dry run or normal run

### ISSUE THREAD

**Issue by yl-coder** [inforion/youtrack-telegram-bot#1]
Hi,

When i ran my dry run or normal run, no data appeared on the console. the connection to youtrack is successfully which listed down all the issues.

My configuration as follows:

 ...},
  "timestampFilePath": "temp/timestamp.txt",
  // or null for all
  "activityCategories": null,
  "minutesGroupInterval": 1,
  // folder must exists
  "descriptionMaxChars": 500,
  "taggedCustomFields": ["Priority", "State"],  // for this field hash tag added before value
  "userCustomFields": ["Assignee", "Supervisor"],
  "filterIssues": []  // optional (parse just specified issues, debug purpose)..

In normal run, it just repeatably shows :

09:38:47 WARN   [      Processor.processProject  ]: Issues filter specified: []
09:38:48 WARN   [      Processor.processProject  ]: Issues filter specified: []
09:38:49 WARN   [      Processor.processProject  ]: Issues filter specified: []
09:38:50 WARN   [      Processor.processProject  ]: Issues filter specified: []
09:38:51 WARN   [      Processor.processProject  ]: Issues filter specified: []

Could you advise if it is a configuration issues or server issues?
I'm using youtrack 2019.1

**Comment by yl-coder** [comment]
I do not wish to do any filtering. Could you advise a simple configuration to do that? Would greatly appreciated that.

**Comment by xthebat** [comment]
Yeah, seems it isn't obvious, but if you don't wish filter anything you should place `null` rather then empty list or just not specify this field at all.

**Comment by yl-coder** [comment]
I get this error when i do that.



Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.google.gson.internal.LinkedTreeMap
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor$processIssueCreatedActivity$stringFields$1.invoke(Processor.kt:77)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor$processIssueCreatedActivity$stringFields$1.invoke(Processor.kt:16)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2291)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2308)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2307)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor.processIssueCreatedActivity(Processor.kt:75)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor.access$processIssueCreatedActivity(Processor.kt:16)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor$getProcessorBy$1.invoke(Processor.kt:140)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor$getProcessorBy$1.invoke(Processor.kt:16)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor.processActivitiesByCategory(Processor.kt:178)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor.access$processActivitiesByCategory(Processor.kt:16)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor$processIssue$$inlined$forEach$lambda$1$1.accept(Processor.kt:260)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor$processIssue$$inlined$forEach$lambda$1$1.accept(Processor.kt:16)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor$processIssue$$inlined$forEach$lambda$1.accept(Processor.kt:259)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor$processIssue$$inlined$forEach$lambda$1.accept(Processor.kt:16)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor.processIssue(Processor.kt:256)
	at ru.inforion.lab403.utils.ytbot.youtrack.Processor.processProject(Processor.kt:294)
	at ru.inforion.lab403.utils.ytbot.Application$Companion.execute(Application.kt:44)
	at ru.inforion.lab403.utils.ytbot.Application$Companion.main(Application.kt:158)
	at ru.inforion.lab403.utils.ytbot.Application.main(Application.kt)

**Comment by yl-coder** [comment]
I believe something went wrong when parsing new created activity

**Comment by xthebat** [comment]
I've added try-catch workaround when parse custom field and logging of error data. Upload it https://github.com/inforion/youtrack-telegram-bot/releases/download/v0.1.2-rc0/youtrack-telegram-bot-0.1.2.tar.gz
Could you please try it and post a log severe message what field can't be parsed.

**Comment by yl-coder** [comment]
ok will try it.
