### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by winsento** [inforion/youtrack-telegram-bot#3]
@xthebat бро, что-то не отправляет сообщения никак.

Test message `./bin/youtrack-telegram-bot -c temp/config.json -tgc "SUPPORT:m:sending testo"`  return timed out exception:
```
INFORION_LOGGING_PRINT: null
INFORION_LOGGING_CONF_PATH: null
14:45:53 INFO   [    Application.main            ]: Namespace(dont_start_services=false, dont_send_messages=false, check_youtrack=null, config=temp/config.json, timestamp=null, daemon=null, check_telegram=SUPPORT:m:sending testo)
14:45:54 WARN   [    Application.main            ]: Starting Telegram connection check with SUPPORT:m:sending testo
Exception in thread "main" java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out
	at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:59)
	at com.pengrad.telegrambot.TelegramBot.execute(TelegramBot.java:41)
	at ru.inforion.lab403.utils.ytbot.telegram.TelegramProxy.execute(TelegramProxy.kt:70)
	at ru.inforion.lab403.utils.ytbot.TelegramChecker.check(TelegramChecker.kt:62)
	at ru.inforion.lab403.utils.ytbot.Application$Companion.main(Application.kt:99)
	at ru.inforion.lab403.utils.ytbot.Application.main(Application.kt)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
	at com.pengrad.telegrambot.impl.TelegramBotClient.send(TelegramBotClient.java:56)
	... 5 more
```

Config:
```
{
  "projects": [
    {
      "name": "SUPPORT",  // 
      "token": "123456789:XXXXXXXX",  // get from @BotFather
      "chatId": 1234567  // get from @get_id_bot
    }
  ],
  "youtrack": {
    "baseUrl": "https://youtrack.xxxx.com",
    "token": "perm:XXXX.XXXX" // bearer auth only
  }
```

P.S. 
Connect to youtrack is OK
`<youtrack-telegram-bot>/bin/youtrack-telegram-bot -c <path-to-config.json> -ytc SUPPORT`

**Comment by davydovvn** [comment]
This exception is due to the fact that the application most likely cannot access the telegram. Ensure that access to Telegram from your IP address is not blocked. In this case, please use the proxy setting.

`.....
"proxy": {  // optional 
    "host":  "xxx.xxx.xxx.xxx",
    "port": xxxx,
    "auth": {  // optional
        "username": "xxxxxxxx",
        "password": "xxxxxxxx"
    },
    "dns": {  // optional (resolve Telegram IP using specified DNS) WARNING: Certificate won't check in this case!
        "ip": "8.8.8.8",
        "port": 53
    }
},
.....`

**Comment by davydovvn** [comment]
This exception is due to the fact that the application most likely cannot access the telegram. Ensure that access to Telegram from your IP address is not blocked. In this case, please use the proxy setting.

```
.....
"proxy": {  // optional 
    "host":  "xxx.xxx.xxx.xxx",
    "port": xxxx,
    "auth": {  // optional
        "username": "xxxxxxxx",
        "password": "xxxxxxxx"
    },
    "dns": {  // optional (resolve Telegram IP using specified DNS) WARNING: Certificate won't check in this case!
        "ip": "8.8.8.8",
        "port": 53
    }
},
.....
```

**Comment by winsento** [comment]
@davydovvn thanks, you was right.
